server.port=${PORT:10000}

spring.datasource.url=jdbc:postgresql://dpg-d7b55v8gjchc73a6bt7g-a.ohio-postgres.render.com:5432/ps08_db
spring.datasource.username=ps08_db_user
spring.datasource.password=Drk9IwGa8h5pfta5tsPfCP7c20l75t26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect